---
# tasks file for Kubernetes_slave

  - name: Configuring yum repository for kubernetes
    yum_repository:
      name: k8s
      description: kuberbetes
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
      enabled: true
      gpgcheck: true
      repo_gpgcheck: true
      gpgkey: >-
        https://packages.cloud.google.com/yum/doc/yum-key.gpg
        https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      file: kubernetes

  - name: installing docker, kubelet, kubeadm, kubectl, n iproute-tc
    package:
      name: "{{ item }}"
    loop:
      - docker
      - kubelet
      - kubeadm
      - kubectl
      - iproute-tc

  - name: enabling kubelet and docker services 
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop: 
      - kubelet
      - docker

  - name: pulling the images
    command: "kubeadm config images pull"

  - name: changing the cgroup driver of docker to systemd
    copy:
      dest: "/etc/docker/daemon.json"
      src: "daemon.json"

  - name: restarting docker
    service:
      name: docker
      state: restarted
      enabled: yes

  - shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"

  - name: clearing caches
    shell: "echo '3' > /proc/sys/vm/drop_caches"

  - name: copying configuration file of k8s
    copy:
      dest: "/etc/sysctl.d/k8s.conf"
      src:  "k8s.conf"

  - name: modifying kernel parameters
    command: "sysctl --system"

  - name: joining the node to master
    shell: "{{ join_command }}"

